// web/src/components/ParticipantTile.tsx
import {Track} from 'livekit-client'
import {
    VideoTrack,
    AudioTrack,
    useParticipantTracks,
    useIsSpeaking
} from '@livekit/components-react'
import {MicOff, Monitor} from 'lucide-react'
import {motion, AnimatePresence} from 'motion/react'
import {ParticipantTileProps} from "../types/components.ts"
import {ConnectionQualityIndicator} from "./ConnectionQualityIndicator.tsx"

export function ParticipantTile({participant, isLocal = false}: ParticipantTileProps) {
    const tracks = useParticipantTracks(
        [Track.Source.Camera, Track.Source.Microphone, Track.Source.ScreenShare],
        participant.identity
    )

    const screenShareTrack = tracks.find(t => t.source === Track.Source.ScreenShare)
    const cameraTrack = tracks.find(t => t.source === Track.Source.Camera)
    const audioTrack = tracks.find(t => t.source === Track.Source.Microphone)

    const isScreenSharing = !!screenShareTrack?.publication && !screenShareTrack.publication.isMuted
    const isCameraOn = !!cameraTrack?.publication && !cameraTrack.publication.isMuted
    const isMuted = !audioTrack?.publication || audioTrack?.publication?.isMuted
    const isSpeaking = useIsSpeaking(participant)

    const initials = participant.name
        ? participant.name.split(' ').map(n => n[0]).join('').toUpperCase().slice(0, 2)
        : participant.identity.slice(0, 2).toUpperCase()

    return (
        <motion.div
            className={`
                relative h-full w-full rounded-[clamp(1rem,2vw,1.5rem)] overflow-hidden bg-[#1A1C22]
                border-2 transition-all duration-300 ease-in-out
                ${isSpeaking ? 'border-brand shadow-brand-glow' : 'border-transparent'}
            `}
            animate={{scale: isSpeaking ? 1.01 : 1}}
        >
            <div className="absolute inset-0 w-full h-full">
                <AnimatePresence mode="wait">
                    {isScreenSharing ? (
                        <motion.div
                            key={`ss-${participant.identity}`}
                            initial={{opacity: 0}} animate={{opacity: 1}} exit={{opacity: 0}}
                            className="w-full h-full bg-black"
                        >
                            <VideoTrack
                                trackRef={screenShareTrack}
                                className="w-full h-full object-contain"
                            />
                        </motion.div>
                    ) : isCameraOn ? (
                        <motion.div
                            key={`cam-${participant.identity}`}
                            initial={{opacity: 0}} animate={{opacity: 1}} exit={{opacity: 0}}
                            className="w-full h-full"
                        >
                            <VideoTrack
                                trackRef={cameraTrack}
                                className="w-full h-full object-cover"
                            />
                        </motion.div>
                    ) : (
                        <motion.div
                            key="init"
                            initial={{opacity: 0}} animate={{opacity: 1}} exit={{opacity: 0}}
                            className="absolute inset-0 flex items-center justify-center bg-avatar-gradient"
                        >
                            <span
                                className="text-[clamp(1.5rem,5vw,3rem)] text-white font-medium tracking-tighter opacity-90">
                                {initials}
                            </span>
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>

            <div
                className="absolute right-[clamp(0.5rem,1.5vw,1rem)] top-[clamp(0.5rem,1.5vw,1rem)] z-50 flex items-center gap-2">
                <ConnectionQualityIndicator participant={participant}/>
            </div>
            <div
                className="absolute bottom-[clamp(0.5rem,1.5vw,1rem)] right-[clamp(0.5rem,1.5vw,1rem)] z-50 flex items-center gap-2">

                <AnimatePresence>
                    {isMuted && (
                        <motion.div
                            key="mute-icon-top"
                            initial={{opacity: 0, scale: 0.8}}
                            animate={{opacity: 1, scale: 1}}
                            exit={{opacity: 0, scale: 0.8}}
                            className="flex size-[clamp(2rem,4.5vw,2.25rem)] items-center justify-center rounded-full border border-white/10 bg-black/50 backdrop-blur-md"
                        >
                            <MicOff className="h-4 w-4 text-white/80"/>
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>


            <div
                className="absolute bottom-[clamp(0.5rem,1.5vw,1rem)] left-[clamp(0.5rem,1.5vw,1rem)] z-10 max-w-[calc(100%-1rem)]">
                <div
                    className="flex items-center gap-1.5 rounded-lg border border-white/10 bg-black/50 px-[clamp(0.625rem,1.8vw,0.75rem)] py-[clamp(0.35rem,1vw,0.45rem)] backdrop-blur-md">
                    {isScreenSharing && <Monitor size={13} className="shrink-0 text-brand"/>}
                    <span className="truncate text-[clamp(0.75rem,1.6vw,0.9375rem)] font-medium text-white">
                        {isLocal ? 'You' : (participant.name ?? participant.identity)}
                    </span>
                </div>
            </div>

            {!isLocal && audioTrack && <AudioTrack trackRef={audioTrack}/>}
        </motion.div>
    )
}

// web-angular/src/app/shared/participant-tile.component.ts
import {AfterViewChecked, Component, ElementRef, OnDestroy, ViewChild, input} from '@angular/core'
import {LocalParticipant, Participant, RemoteParticipant, Track} from 'livekit-client'
import {LucideAngularModule, MicOff, Monitor} from 'lucide-angular'

@Component({
    selector: 'app-participant-tile',
    imports: [LucideAngularModule],
    template: `
        <article class="relative h-full min-h-0 overflow-hidden rounded-xl border bg-slate-100"
                 [class.border-success]="participant().isSpeaking"
                 [class.shadow-[0_0_18px_rgba(34,197,94,.32)]]="participant().isSpeaking"
                 [class.border-slate-300]="!participant().isSpeaking">
            <video #video autoplay playsinline class="absolute inset-0 size-full object-cover"
                   [class.object-contain]="screenSharing"></video>
            <audio #audio autoplay></audio>
            @if (!hasVideo) {
                <div class="absolute inset-0 grid place-items-center bg-gradient-to-br"
                     [class.from-blue-100]="isLocal()" [class.from-emerald-100]="!isLocal()" [class.to-slate-100]="true">
                    <span class="grid size-14 place-items-center rounded-full border text-2xl font-semibold"
                          [class.border-brand]="isLocal()" [class.text-blue-700]="isLocal()"
                          [class.border-success]="!isLocal()" [class.text-emerald-700]="!isLocal()">{{ initials }}</span>
                </div>
            }
            <div class="absolute bottom-0 left-0 right-0 flex items-center justify-between bg-gradient-to-t from-black/80 px-3 pb-3 pt-8 text-xs text-white">
                <span class="truncate font-semibold">{{ isLocal() ? 'You' : participant().name || participant().identity }} @if (isHost) {
                    <small class="ml-1 text-amber">HOST</small>
                }</span>
                <span class="flex items-center gap-2">@if (screenSharing) {
                    <lucide-icon [img]="Monitor" class="size-4 text-brand"/>
                }
                    @if (muted) {
                        <lucide-icon [img]="MicOff" class="size-4 text-danger"/>
                    }</span>
            </div>
        </article>
    `
})
export class ParticipantTileComponent implements AfterViewChecked, OnDestroy {
    readonly participant = input.required<LocalParticipant | RemoteParticipant>()
    readonly isLocal = input(false)
    @ViewChild('video') private video?: ElementRef<HTMLVideoElement>
    @ViewChild('audio') private audio?: ElementRef<HTMLAudioElement>
    protected readonly MicOff = MicOff
    protected readonly Monitor = Monitor
    hasVideo = false
    screenSharing = false
    muted = true
    isHost = false
    initials = ''
    private attached: HTMLMediaElement | null = null
    private attachedTrack: Track | null = null
    private attachedAudio: HTMLMediaElement | null = null
    private attachedAudioTrack: Track | null = null

    ngAfterViewChecked(): void {
        const participant = this.participant()
        const camera = participant.getTrackPublication(Track.Source.Camera)
        const screen = participant.getTrackPublication(Track.Source.ScreenShare)
        const selected = screen?.track && !screen.isMuted ? screen.track : camera?.track && !camera.isMuted ? camera.track : undefined
        this.screenSharing = Boolean(screen?.track && !screen.isMuted)
        this.hasVideo = Boolean(selected)
        this.muted = !participant.getTrackPublication(Track.Source.Microphone)?.isSubscribed || Boolean(participant.getTrackPublication(Track.Source.Microphone)?.isMuted)
        this.isHost = participant.metadata === 'host'
        this.initials = (participant.name || participant.identity).split(/\s+/).map(part => part[0]).join('').slice(0, 2).toUpperCase()
        const video = this.video?.nativeElement
        if (video && selected !== this.attachedTrack) {
            if (this.attachedTrack) this.attachedTrack.detach(video)
            if (selected) selected.attach(video)
            this.attached = selected ? video : null
            this.attachedTrack = selected ?? null
        }
        const audio = this.audio?.nativeElement
        const microphone = participant.getTrackPublication(Track.Source.Microphone)?.track
        if (!this.isLocal() && audio && microphone !== this.attachedAudioTrack) {
            if (this.attachedAudioTrack) this.attachedAudioTrack.detach(audio)
            if (microphone) microphone.attach(audio)
            this.attachedAudio = microphone ? audio : null
            this.attachedAudioTrack = microphone ?? null
        }
    }

    ngOnDestroy(): void {
        this.attached && this.attached.replaceChildren();
        this.attachedAudio && this.attachedAudio.replaceChildren()
    }
}
