// web/src/pages/InCallPage.tsx
import {useEffect, useState, useCallback, useRef} from 'react'
import {useNavigate, useLocation, useParams} from 'react-router-dom'
import {RoomEvent} from 'livekit-client'
import {RoomContext} from '@livekit/components-react'
import {useLiveKitRoom} from '../hooks/useLiveKitRoom'
import {VideoGrid} from '../components/VideoGrid'
import {Toolbar} from '../components/Toolbar'
import {ReconnectOverlay} from '../components/ReconnectOverlay'
import {RecordingIndicator} from '../components/RecordingIndicator'
import {endMeeting, getMeeting} from '../api/MeetingApi.ts'

export function InCallPage() {
    const navigate = useNavigate()
    const {roomId} = useParams<{ roomId: string }>()

    const location = useLocation()
    const callState = (location.state as { token?: string; participantName?: string } | null) ?? null
    const token = callState?.token
    const participantName = callState?.participantName

    const {
        room,
        localParticipant,
        remoteParticipants,
        isConnected,
        isReconnecting,
        isRecording,
        error,
    } = useLiveKitRoom(token, participantName)

    const [isMuted, setIsMuted] = useState(false)
    const [isCameraOff, setIsCameraOff] = useState(false)
    const [isScreenSharing, setIsScreenSharing] = useState(false)
    const [isHost, setIsHost] = useState(false)


    useEffect(() => {
        if (!token) return
        try {
            const payload = JSON.parse(atob(token.split('.')[1]))
            setIsHost(payload.metadata === 'host')
        } catch {
            setIsHost(false)
        }
    }, [token])

    const [durationSeconds, setDurationSeconds] = useState(0)
    const [durationLimitSeconds, setDurationLimitSeconds] = useState<number | null>(null)
    const startedAtRef = useRef<number | null>(null)

    useEffect(() => {
        if (!isConnected || !roomId) return

        getMeeting(roomId).then(meeting => {
            if (meeting.durationLimitMinutes) {
                setDurationLimitSeconds(meeting.durationLimitMinutes * 60)
            }
        }).catch(() => {
        })

        const interval = setInterval(async () => {
            if (startedAtRef.current === null) {
                try {
                    const meeting = await getMeeting(roomId)
                    if (meeting.startedAt) {
                        startedAtRef.current = new Date(meeting.startedAt).getTime()
                    }
                } catch {
                }
            }

            if (startedAtRef.current !== null) {
                setDurationSeconds(Math.floor((Date.now() - startedAtRef.current) / 1000))
            } else {
                setDurationSeconds(s => s + 1)
            }
        }, 1000)

        return () => clearInterval(interval)
    }, [isConnected, roomId])

    const navigateToPostCall = useCallback(async () => {
        let participants: { name: string; initials: string }[] = remoteParticipants.map(p => ({
            name: p.name ?? p.identity,
            initials: (p.name ?? p.identity).slice(0, 2).toUpperCase(),
        }))

        let recordingUrl: string | null = null
        let participantRecordings: { name: string; url: string }[] = []

        if (roomId) {
            try {
                const meeting = await getMeeting(roomId)
                recordingUrl = meeting.recording?.presignedUrl ?? null
                participantRecordings = (meeting.participants ?? [])
                    .filter((p: any) => p.recordingPresignedUrl)
                    .map((p: any) => ({name: p.name, url: p.recordingPresignedUrl}))

                if (meeting.participants?.length > 0) {
                    participants = (meeting.participants ?? [])
                        .map((p: any) => ({
                            name: p.name,
                            initials: p.name.slice(0, 2).toUpperCase(),
                            joinedAt: p.joinedAt ?? null,
                            leftAt: p.leftAt ?? null,
                        }))
                }
            } catch {
            }
        }

        navigate('/post-call', {
            state: {durationSeconds, participants, recordingUrl, participantRecordings, isHost},
        })
    }, [roomId, remoteParticipants, localParticipant, durationSeconds, navigate, isHost])

    useEffect(() => {
        if (!room) return
        room.on(RoomEvent.Disconnected, navigateToPostCall)
        return () => {
            room.off(RoomEvent.Disconnected, navigateToPostCall)
        }
    }, [room, navigateToPostCall])

    const handleToggleMute = useCallback(async () => {
        if (!localParticipant) return
        await localParticipant.setMicrophoneEnabled(isMuted)
        setIsMuted(m => !m)
    }, [localParticipant, isMuted])

    const handleToggleCamera = useCallback(async () => {
        if (!localParticipant) return
        await localParticipant.setCameraEnabled(isCameraOff)
        setIsCameraOff(c => !c)
    }, [localParticipant, isCameraOff])

    const handleToggleScreenShare = useCallback(async () => {
        if (!localParticipant) return
        await localParticipant.setScreenShareEnabled(!isScreenSharing)
        setIsScreenSharing(s => !s)
    }, [localParticipant, isScreenSharing])

    const handleEndCall = useCallback(async () => {
        if (!roomId) return
        try {
            if (isHost) {
                endMeeting(roomId)
            }
        } catch {
        } finally {
            room?.disconnect()
        }
    }, [room, roomId, isHost])

    const timerColor = durationLimitSeconds === null
        ? 'text-text-secondary'
        : durationSeconds >= durationLimitSeconds
            ? 'text-red-500'
            : durationSeconds >= durationLimitSeconds - 300
                ? 'text-yellow-400'
                : 'text-text-secondary'

    if (!token) {
        return (
            <div className="h-[100dvh] overflow-hidden bg-page">
                <div className="flex h-full items-center justify-center p-4">
                    <div className="text-center">
                        <p className="mb-4 text-lg text-text-error">Missing join token.</p>
                    <button
                        onClick={() => navigate('/')}
                        className="px-6 py-3 rounded-xl bg-brand text-text-primary hover:scale-[1.02] active:scale-[0.98] transition-transform duration-150"
                    >
                        Go back
                    </button>
                </div>
                </div>
            </div>
        )
    }

    if (error) {
        return (
            <div className="h-[100dvh] overflow-hidden bg-page">
                <div className="flex h-full items-center justify-center p-4">
                    <div className="text-center">
                        <p className="mb-2 text-lg text-text-error">Failed to connect to the call.</p>
                        <p className="mb-6 text-sm text-text-secondary">{error.message}</p>
                    <button
                        onClick={() => navigate('/')}
                        className="px-6 py-3 rounded-xl bg-brand text-text-primary hover:scale-[1.02] active:scale-[0.98] transition-transform duration-150"
                    >
                        Go back
                    </button>
                </div>
                </div>
            </div>
        )
    }

    return (
        <RoomContext.Provider value={room ?? undefined}>
            <div className="h-[100dvh] overflow-hidden bg-page">
                <div
                    className="flex h-full min-h-0 flex-col">
                    <div
                        className="shrink-0 border-b border-border bg-surface px-[clamp(0.75rem,2vw,1.5rem)] py-[clamp(0.625rem,1.6vh,0.875rem)] backdrop-blur-[20px]">
                        <div className="flex flex-wrap items-center justify-between gap-[clamp(0.5rem,1.5vw,0.75rem)]">
                            <span
                                className="min-w-0 flex-1 truncate text-[clamp(0.75rem,1.7vw,0.875rem)] font-mono text-text-secondary">
                                {roomId}
                            </span>
                            <div className="flex flex-wrap items-center justify-end gap-[clamp(0.5rem,1.5vw,0.75rem)]">
                                <RecordingIndicator isRecording={isRecording}/>
                                <span
                                    className={`text-[clamp(0.75rem,1.7vw,0.875rem)] font-mono tabular-nums ${timerColor}`}>
                                    {String(Math.floor(durationSeconds / 60)).padStart(2, '0')}:
                                    {String(durationSeconds % 60).padStart(2, '0')}
                                    {durationLimitSeconds !== null && (
                                        <> / {String(Math.floor(durationLimitSeconds / 60)).padStart(2, '0')}:00</>
                                    )}
                                </span>
                            </div>
                        </div>
                    </div>

                    <div className="relative flex min-h-0 flex-1 flex-col overflow-hidden">
                        <VideoGrid
                            localParticipant={localParticipant}
                            remoteParticipants={remoteParticipants}
                        />
                        <ReconnectOverlay isReconnecting={isReconnecting}/>
                    </div>

                    <Toolbar
                        isMuted={isMuted}
                        isCameraOff={isCameraOff}
                        isScreenSharing={isScreenSharing}
                        onToggleMute={handleToggleMute}
                        onToggleCamera={handleToggleCamera}
                        onToggleScreenShare={handleToggleScreenShare}
                        onEndCall={handleEndCall}
                    />
                </div>
            </div>
        </RoomContext.Provider>
    )
}

// web-angular/src/app/pages/in-call-page.component.ts
import {Component, OnDestroy, OnInit, computed, inject, signal} from '@angular/core'
import {ActivatedRoute, Router} from '@angular/router'
import {firstValueFrom} from 'rxjs'
import {LucideAngularModule, Mic, MicOff, MonitorUp, PhoneOff, Video, VideoOff} from 'lucide-angular'
import {RoomEvent} from 'livekit-client'
import {readJoinIdentity} from '../core/jwt.util'
import {LiveKitRoomService} from '../core/livekit-room.service'
import {MeetingApiService} from '../core/meeting-api.service'
import {MeetingStateService} from '../core/meeting-state.service'
import {formatDuration} from '../core/time.util'
import {SessionsHeaderComponent} from '../shared/sessions-header.component'
import {ParticipantTileComponent} from '../shared/participant-tile.component'

@Component({
    selector: 'app-in-call-page',
    imports: [SessionsHeaderComponent, ParticipantTileComponent, LucideAngularModule],
    template: `
        <div class="flex h-screen flex-col overflow-hidden bg-page">
            <app-sessions-header [title]="title()"/>
            @if (!token) {
                <main class="grid flex-1 place-items-center p-6 text-center">
                    <div><p class="text-lg text-danger">Missing join token.</p>
                        <button class="btn-primary mt-4" (click)="goHome()">Go back</button>
                    </div>
                </main>
            } @else if (livekit.error()) {
                <main class="grid flex-1 place-items-center p-6 text-center">
                    <div><p class="text-lg text-danger">Failed to connect to the call.</p>
                        <p class="mt-2 max-w-md text-sm text-muted">{{ livekit.error() }}</p>
                        <button class="btn-primary mt-5" (click)="goHome()">Go back</button>
                    </div>
                </main>
            } @else {
                <div class="flex min-h-0 flex-1 flex-col">
                    <div class="flex items-center justify-between border-b border-line bg-white px-5 py-3">
                        <div class="text-xs text-muted">{{ title() || roomId }}</div>
                        <div class="flex items-center gap-4"><span
                                class="rounded border border-danger/30 bg-danger/10 px-2 py-1 text-[11px] font-bold text-danger"
                                [class.invisible]="!livekit.recording()">● REC</span><span
                                class="font-mono text-sm text-slate-600"
                                [class.text-danger]="limitSeconds() && elapsed() >= limitSeconds()">{{ duration() }} @if (limitSeconds()) {
                            / {{ limitDuration() }}
                        }</span><span class="text-xs text-muted">{{ participantCount() }} participants</span></div>
                    </div>
                    <main class="relative min-h-0 flex-1 p-3">
                        <div class="grid size-full gap-2"
                             [style.grid-template-columns]="gridColumns()">@for (participant of allParticipants(); track participant.identity) {
                            <app-participant-tile [participant]="participant"
                                                  [isLocal]="participant.identity === livekit.localParticipant()?.identity"/>
                        }</div>@if (!allParticipants().length) {
                        <div class="absolute inset-0 grid place-items-center text-sm text-muted">Connecting to
                            meeting…
                        </div>
                    }
                        @if (livekit.reconnecting()) {
                            <div class="absolute inset-0 z-10 grid place-items-center bg-page/85 text-center backdrop-blur">
                                <div><span
                                        class="mx-auto block size-10 animate-spin rounded-full border-4 border-line border-t-brand"></span>
                                    <p class="mt-4 font-semibold text-slate-900">Reconnecting…</p>
                                    <p class="mt-1 text-sm text-muted">Please wait while we restore your connection.</p>
                                </div>
                            </div>
                        }</main>
                    <footer class="flex shrink-0 items-center justify-center border-t border-line bg-white p-3">
                        <div class="flex items-center gap-3">
                            <button class="toolbar" [class.toolbar-danger]="muted()" (click)="toggleMute()">
                                <lucide-icon [img]="muted() ? MicOff : Mic" class="size-5"/>
                            </button>
                            <button class="toolbar" [class.toolbar-danger]="cameraOff()" (click)="toggleCamera()">
                                <lucide-icon [img]="cameraOff() ? VideoOff : Video" class="size-5"/>
                            </button>
                            <button class="toolbar" [class.toolbar-danger]="sharing()" (click)="toggleScreenShare()">
                                <lucide-icon [img]="MonitorUp" class="size-5"/>
                            </button>
                            <button
                                    class="grid size-12 place-items-center rounded-xl bg-danger text-white transition hover:bg-red-700"
                                    (click)="endCall()">
                                <lucide-icon [img]="PhoneOff" class="size-5"/>
                            </button>
                        </div>
                    </footer>
                </div>
            }
        </div>
    `,
    styles: `.toolbar {
        @apply grid size-12 place-items-center rounded-xl border border-line bg-white text-slate-600 shadow-md shadow-slate-200/70 transition hover:-translate-y-px hover:border-brand hover:text-brand hover:shadow-lg;
    }

    .toolbar-danger {
        @apply border-danger/50 bg-danger/15 text-danger shadow-red-100;
    }`
})
export class InCallPageComponent implements OnInit, OnDestroy {
    private readonly route = inject(ActivatedRoute);
    private readonly router = inject(Router);
    protected readonly livekit = inject(LiveKitRoomService);
    private readonly api = inject(MeetingApiService);
    private readonly state = inject(MeetingStateService)
    readonly roomId = this.route.snapshot.paramMap.get('roomId') ?? '';
    readonly token = this.route.snapshot.queryParamMap.get('token');
    private readonly identity = readJoinIdentity(this.token)
    readonly title = signal('');
    readonly elapsed = signal(0);
    readonly limitSeconds = signal(0);
    readonly muted = signal(false);
    readonly cameraOff = signal(false);
    readonly sharing = signal(false)
    readonly allParticipants = computed(() => [...(this.livekit.localParticipant() ? [this.livekit.localParticipant()!] : []), ...this.livekit.remoteParticipants()])
    readonly participantCount = computed(() => this.allParticipants().length)
    readonly duration = computed(() => formatDuration(this.elapsed()));
    readonly limitDuration = computed(() => formatDuration(this.limitSeconds()));
    readonly gridColumns = computed(() => `repeat(${this.participantCount() <= 1 ? 1 : this.participantCount() <= 4 ? 2 : this.participantCount() <= 9 ? 3 : 4}, minmax(0, 1fr))`)
    private timer?: ReturnType<typeof setInterval>;
    private leaving = false
    protected readonly Mic = Mic;
    protected readonly MicOff = MicOff;
    protected readonly MonitorUp = MonitorUp;
    protected readonly PhoneOff = PhoneOff;
    protected readonly Video = Video;
    protected readonly VideoOff = VideoOff

    async ngOnInit(): Promise<void> {
        if (!this.token) return
        this.api.getMeeting(this.roomId).subscribe({
            next: meeting => {
                this.title.set(meeting.title);
                this.limitSeconds.set(meeting.durationLimitMinutes * 60);
                const started = meeting.startedAt ? new Date(meeting.startedAt).getTime() : Date.now();
                this.elapsed.set(Math.max(0, Math.floor((Date.now() - started) / 1000)));
                this.timer = setInterval(() => this.elapsed.update(value => value + 1), 1000)
            }
        })
        const cameraEnabled = this.route.snapshot.queryParamMap.get('cameraEnabled') !== 'false'
        const microphoneEnabled = this.route.snapshot.queryParamMap.get('microphoneEnabled') !== 'false'
        this.cameraOff.set(!cameraEnabled)
        this.muted.set(!microphoneEnabled)
        await this.livekit.connect(this.token, this.route.snapshot.queryParamMap.get('name') || this.identity.name, this.route.snapshot.queryParamMap.get('camera') || undefined, this.route.snapshot.queryParamMap.get('microphone') || undefined, cameraEnabled, microphoneEnabled)
        this.livekit.room()?.on(RoomEvent.Disconnected, () => void this.finish())
    }

    async toggleMute(): Promise<void> {
        const participant = this.livekit.localParticipant();
        if (!participant) return;
        await participant.setMicrophoneEnabled(this.muted());
        this.muted.update(value => !value)
    }

    async toggleCamera(): Promise<void> {
        const participant = this.livekit.localParticipant();
        if (!participant) return;
        await participant.setCameraEnabled(this.cameraOff());
        this.cameraOff.update(value => !value)
    }

    async toggleScreenShare(): Promise<void> {
        const participant = this.livekit.localParticipant();
        if (!participant) return;
        await participant.setScreenShareEnabled(!this.sharing());
        this.sharing.update(value => !value)
    }

    async endCall(): Promise<void> {
        if (this.identity.isHost) {
            try {
                await firstValueFrom(this.api.endMeeting(this.roomId))
            } catch {
            }
        }
        this.livekit.disconnect();
        await this.finish()
    }

    private async finish(): Promise<void> {
        if (this.leaving) return;
        this.leaving = true;
        clearInterval(this.timer);
        let meeting = null;
        try {
            meeting = await firstValueFrom(this.api.getMeeting(this.roomId))
        } catch {
        }
        this.state.setCallSummary({
            roomId: this.roomId,
            durationSeconds: this.elapsed(),
            isHost: this.identity.isHost,
            meeting
        });
        await this.router.navigateByUrl('/post-call')
    }

    goHome(): void {
        this.router.navigateByUrl('/')
    }

    ngOnDestroy(): void {
        clearInterval(this.timer);
        if (!this.leaving) this.livekit.disconnect()
    }
}
