// web/src/pages/PostCallPage.tsx
import {useNavigate, useLocation} from "react-router-dom";
import {Download, Home, Clock, Users, Phone, Plus} from "lucide-react";
import {useMountTransition} from "../hooks/useMountTransition";
import {useIsEmbedded} from "../hooks/useIsEmbedded";
import {useViewportScale} from "../hooks/useViewportScale";
import {PostCallState} from "../types/pages.ts";
import {FALLBACK_ATTENDEES} from "../constants/constants.ts";
import {formatDuration} from "../utils/utils.ts";
import {formatTime} from "../utils/utils.ts";

export function PostCallPage() {
    const navigate = useNavigate();
    const mounted = useMountTransition();
    const isEmbedded = useIsEmbedded();
    const {viewportRef, contentRef, scale, contentWidth, scaledWidth, scaledHeight} = useViewportScale();

    const location = useLocation();
    const state = (location.state ?? {}) as PostCallState;

    const duration = state.durationSeconds != null
        ? formatDuration(state.durationSeconds)
        : "00:00";

    const participants = state.participants ?? FALLBACK_ATTENDEES;
    const recordingUrl = state.recordingUrl ?? null;
    const participantRecordings = state.participantRecordings ?? [];
    const isHost = state.isHost ?? false;
    const showStandaloneActions = !isEmbedded;
    const hasRecordingActions = isHost && (!!recordingUrl || participantRecordings.length > 0);
    const hasActions = hasRecordingActions || showStandaloneActions;

    return (
        <div className="h-[100dvh] overflow-hidden bg-page">
            <div
                ref={viewportRef}
                className="flex h-full w-full items-center justify-center p-[clamp(0.5rem,2vw,1.5rem)]"
            >
                <div
                    className="relative shrink-0"
                    style={{
                        width: scaledWidth ? `${scaledWidth}px` : '100%',
                        height: scaledHeight ? `${scaledHeight}px` : 'auto',
                    }}
                >
                    <div
                        ref={contentRef}
                        className={`absolute left-1/2 top-0 transition-all duration-500 will-change-transform ${
                            mounted ? "opacity-100 translate-y-0" : "opacity-0 translate-y-5"
                        }`}
                        style={{
                            width: contentWidth ? `${contentWidth}px` : '100%',
                            transform: `translateX(-50%) scale(${scale})`,
                            transformOrigin: 'top center',
                        }}
                    >
                        <div className="mx-auto flex w-full max-w-5xl flex-col gap-[clamp(0.875rem,2.4vh,1.5rem)]">
                            <div className="text-center">
                                <div
                                    className={`
                            mb-4 inline-flex size-[clamp(4.5rem,10vw,5rem)] items-center justify-center rounded-full
                            border-2 border-brand bg-brand-muted
                            transition-all duration-500 delay-200
                            ${mounted ? "opacity-100 scale-100" : "opacity-0 scale-0"}
                        `}
                                >
                                    <Phone
                                        className="h-[clamp(2rem,4vw,2.5rem)] w-[clamp(2rem,4vw,2.5rem)] text-brand"/>
                                </div>
                                <h1 className="mb-2 text-[clamp(1.75rem,4vw,2.5rem)] text-text-primary">Meeting
                                    Ended</h1>
                                <p className="text-[clamp(0.875rem,2vw,1rem)] text-text-secondary">
                                    Thanks for joining! Here's a summary of your call.
                                </p>
                            </div>

                            <div
                                className={`grid gap-[clamp(0.875rem,2vw,1.25rem)] ${hasActions ? 'lg:grid-cols-[minmax(0,1.1fr)_minmax(18rem,0.9fr)]' : ''}`}>
                                <div
                                    className={hasActions ? '' : 'mx-auto w-full max-w-3xl'}
                                >
                                    <div
                                    className={`
                        rounded-[clamp(1rem,2vw,1.5rem)] border border-border bg-surface p-[clamp(1rem,2.4vw,2rem)] backdrop-blur-[20px]
                        transition-all duration-500 delay-300
                        ${mounted ? "opacity-100 translate-y-0" : "opacity-0 translate-y-5"}
                    `}
                                >
                                    <div className="grid gap-[clamp(0.75rem,1.8vw,1rem)] sm:grid-cols-2">
                                        <div
                                            className="flex items-center gap-[clamp(0.75rem,1.8vw,1rem)] rounded-[clamp(0.875rem,1.8vw,1rem)] border border-border bg-page/20 p-[clamp(0.75rem,1.8vw,1rem)]">
                                            <div
                                                className="flex size-[clamp(2.75rem,5vw,3rem)] shrink-0 items-center justify-center rounded-xl bg-brand-muted">
                                                <Clock className="h-5 w-5 text-brand"/>
                                            </div>
                                            <div className="min-w-0">
                                                <div className="mb-1 text-sm text-text-secondary">Duration</div>
                                                <div
                                                    className="text-[clamp(1.125rem,2.4vw,1.5rem)] text-text-primary">{duration}</div>
                                            </div>
                                        </div>

                                        <div
                                            className="flex items-center gap-[clamp(0.75rem,1.8vw,1rem)] rounded-[clamp(0.875rem,1.8vw,1rem)] border border-border bg-page/20 p-[clamp(0.75rem,1.8vw,1rem)]">
                                            <div
                                                className="flex size-[clamp(2.75rem,5vw,3rem)] shrink-0 items-center justify-center rounded-xl bg-brand-muted">
                                                <Users className="h-5 w-5 text-brand"/>
                                            </div>
                                            <div className="min-w-0">
                                                <div className="mb-1 text-sm text-text-secondary">Participants</div>
                                                <div className="text-[clamp(1rem,2.2vw,1.25rem)] text-text-primary">
                                                    {participants.length} people
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div
                                        className="mt-[clamp(0.875rem,2vh,1.25rem)] grid gap-[clamp(0.625rem,1.5vw,0.875rem)] sm:grid-cols-2">
                                        {participants.map((attendee, index) => (
                                            <div
                                                key={`${attendee.name}-${index}`}
                                                className={`
                                    flex items-center gap-[clamp(0.625rem,1.5vw,0.75rem)] rounded-[clamp(0.875rem,1.8vw,1rem)] border border-border/70 bg-page/10 p-[clamp(0.625rem,1.5vw,0.875rem)]
                                    transition-all duration-300
                                    ${mounted ? "opacity-100 translate-x-0" : "opacity-0 -translate-x-5"}
                                `}
                                                style={{transitionDelay: `${400 + index * 50}ms`}}
                                            >
                                                <div
                                                    className="flex size-[clamp(2.25rem,4vw,2.5rem)] shrink-0 items-center justify-center rounded-full bg-avatar-gradient">
                                                <span className="text-sm font-semibold text-text-primary">
                                                    {attendee.initials}
                                                </span>
                                                </div>
                                                <div className="min-w-0 flex-1">
                                                    <div
                                                        className="truncate text-[clamp(0.875rem,1.8vw,1rem)] text-text-primary">
                                                        {attendee.name}
                                                    </div>
                                                    {(attendee as any).joinedAt == null ? (
                                                        <div className="text-xs text-text-error">Never joined</div>
                                                    ) : (
                                                        <div className="truncate text-xs text-text-secondary">
                                                            Joined: {formatTime((attendee as any).joinedAt)}
                                                        </div>
                                                    )}
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                                </div>

                                {hasActions && (
                                    <div
                                    className={`
                        grid auto-rows-fr gap-3 transition-all duration-500 delay-500
                        ${mounted ? "opacity-100 translate-y-0" : "opacity-0 translate-y-5"}
                    `}
                                >
                                    {isHost && recordingUrl && (
                                        <a
                                            href={recordingUrl}
                                            download
                                            className="
                                flex min-h-[3.5rem] w-full items-center justify-center gap-3 rounded-[clamp(0.875rem,2vw,1rem)] bg-brand px-4 py-[clamp(0.875rem,1.8vh,1rem)] text-text-primary shadow-brand-glow
                                transition-transform duration-150
                                hover:scale-[1.02] active:scale-[0.98]
                            "
                                        >
                                            <Download className="h-5 w-5 shrink-0"/>
                                            <span className="min-w-0 truncate">Download Recording</span>
                                        </a>
                                    )}

                                    {isHost && participantRecordings.map(({name, role, url}) => (
                                        <a
                                            key={name}
                                            href={url}
                                            download
                                            className="
                                flex min-h-[3.5rem] w-full items-center justify-center gap-3 rounded-[clamp(0.875rem,2vw,1rem)] bg-brand px-4 py-[clamp(0.875rem,1.8vh,1rem)] text-text-primary shadow-brand-glow
                                transition-transform duration-150
                                hover:scale-[1.02] active:scale-[0.98]
                            "
                                            title={role === 'host' ? 'Download Host Recording' : `Download ${name}'s Recording`}
                                        >
                                            <Download className="h-5 w-5 shrink-0"/>
                                            <span className="min-w-0 truncate">
                                                {role === 'host' ? 'Download Host Recording' : `Download ${name}'s Recording`}
                                            </span>
                                        </a>
                                    ))}

                                        {showStandaloneActions && (
                                        <button
                                            onClick={() => navigate("/")}
                                            className="
                            flex min-h-[3.5rem] w-full items-center justify-center gap-3 rounded-[clamp(0.875rem,2vw,1rem)] bg-brand px-4 py-[clamp(0.875rem,1.8vh,1rem)] text-text-primary shadow-brand-glow
                            transition-transform duration-150
                            hover:scale-[1.02] active:scale-[0.98]
                        "
                                        >
                                            <Plus className="h-5 w-5 shrink-0"/>
                                            <span className="min-w-0 truncate">Start a New Meeting</span>
                                        </button>
                                    )}

                                        {showStandaloneActions && (
                                        <button
                                            onClick={() => navigate("/")}
                                            className="
                            flex min-h-[3.5rem] w-full items-center justify-center gap-3 rounded-[clamp(0.875rem,2vw,1rem)] border border-border bg-surface px-4 py-[clamp(0.875rem,1.8vh,1rem)] text-text-primary
                            transition-transform duration-150
                            hover:scale-[1.02] active:scale-[0.98]
                        "
                                        >
                                            <Home className="h-5 w-5 shrink-0"/>
                                            <span className="min-w-0 truncate">Back to Dashboard</span>
                                        </button>
                                    )}
                                </div>
                                )}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

// web-angular/src/app/pages/post-call-page.component.ts
import {Component, computed, inject} from '@angular/core'
import {RouterLink} from '@angular/router'
import {Download, LucideAngularModule, Plus, Users} from 'lucide-angular'
import {MeetingStateService} from '../core/meeting-state.service'
import {formatDuration, formatTime} from '../core/time.util'
import {SessionsHeaderComponent} from '../shared/sessions-header.component'

@Component({
    selector: 'app-post-call-page',
    imports: [RouterLink, SessionsHeaderComponent, LucideAngularModule],
    template: `
        <div class="min-h-screen bg-page">
            <app-sessions-header/>
            @if (summary(); as call) {
                <main class="mx-auto w-full max-w-[632px] px-5 py-9"><h1 class="text-2xl font-semibold text-white">
                    Meeting Ended</h1>
                    <p class="mt-2 text-sm text-muted">{{ call.meeting?.title || 'Meeting summary' }}</p>
                    <div class="mt-8 grid grid-cols-3 gap-3">
                        <div class="session-card p-4"><p class="text-xs text-muted">Duration</p>
                            <p class="mt-2 font-mono text-lg font-bold text-white">{{ duration() }}</p></div>
                        <div class="session-card p-4"><p class="text-xs text-muted">Participants joined</p>
                            <p class="mt-2 font-mono text-lg font-bold text-white">{{ joinedCount() }}
                                / {{ participants().length }}</p></div>
                        <div class="session-card p-4"><p class="text-xs text-muted">Recording</p>
                            <p class="mt-2 font-mono text-lg font-bold"
                               [class.text-success]="call.meeting?.recordingEnabled"
                               [class.text-muted]="!call.meeting?.recordingEnabled">{{ call.meeting?.recording ? call.meeting?.recording?.height + 'p' : 'Off' }}</p>
                        </div>
                    </div>
                    <section class="session-card mt-6 p-5"><h2 class="section-label border-b border-[#1c293d] pb-3">
                        Participant activity</h2>
                        <div class="mt-3 divide-y divide-[#1c293d]">@for (participant of participants(); track participant.id) {
                            <article class="flex items-center gap-3 py-3"><span
                                    class="grid size-8 place-items-center rounded-full border border-brand/40 bg-brand/10 text-[10px] font-semibold text-[#9bc2ff]">{{ initials(participant.name) }}</span>
                                <div class="min-w-0 flex-1"><p
                                        class="truncate text-sm font-semibold text-white">{{ participant.name }} @if (participant.role === 'host') {
                                    <small class="ml-1 text-[9px] text-amber">♛ HOST</small>
                                }</p></div>@if (participant.joinedAt) {
                                    <div class="grid grid-cols-2 gap-3 text-right font-mono text-[10px] text-muted">
                                        <span>Joined<br><b
                                                class="font-normal text-[#a4bbdc]">{{ time(participant.joinedAt) }}</b></span><span>Left<br><b
                                            class="font-normal text-[#a4bbdc]">{{ time(participant.leftAt) }}</b></span>
                                    </div>
                                } @else {
                                    <span class="rounded border border-line px-2 py-1 text-[10px] text-muted">Did not join</span>
                                }</article>
                        }</div>
                    </section>
                    <div class="mt-5 flex flex-wrap gap-3">@if (call.isHost && call.meeting?.recording?.presignedUrl) {
                        <a [href]="call.meeting?.recording?.presignedUrl" download class="btn-secondary">
                            <lucide-icon [img]="Download" class="size-4"/>
                            Download Recording</a>
                    }
                        @if (call.isHost) {
                            @for (participant of participants(); track participant.id) {
                                @if (participant.recordingPresignedUrl) {
                                    <a [href]="participant.recordingPresignedUrl" download class="btn-secondary">
                                        <lucide-icon [img]="Download" class="size-4"/>
                                        {{ participant.name }} recording</a>
                                }
                            }
                        }<a routerLink="/" class="btn-primary">
                            <lucide-icon [img]="Plus" class="size-4"/>
                            New Meeting</a></div>
                </main>
            } @else {
                <main class="grid min-h-[calc(100vh-51px)] place-items-center p-6 text-center">
                    <div><p class="text-lg text-white">No call summary is available.</p><a routerLink="/"
                                                                                           class="btn-primary mt-5">New
                        Meeting</a></div>
                </main>
            }
        </div>
    `
})
export class PostCallPageComponent {
    private readonly state = inject(MeetingStateService);
    protected readonly summary = this.state.callSummary;
    readonly participants = computed(() => this.summary()?.meeting?.participants ?? []);
    readonly duration = computed(() => formatDuration(this.summary()?.durationSeconds ?? 0));
    readonly joinedCount = computed(() => this.participants().filter(item => item.joinedAt).length);
    protected readonly Download = Download;
    protected readonly Plus = Plus;
    protected readonly Users = Users

    initials(value: string): string {
        return value.split(/\s+/).map(part => part[0]).join('').slice(0, 2).toUpperCase()
    }

    time(value: string | null): string {
        return formatTime(value)
    }
}
