// web-angular/src/app/pages/create-meeting-page.component.ts
import {Component, inject, signal} from '@angular/core'
import {FormArray, FormBuilder, ReactiveFormsModule, Validators} from '@angular/forms'
import {Router} from '@angular/router'
import {finalize} from 'rxjs'
import {
    ChevronDown,
    FileUp,
    LucideAngularModule,
    Monitor,
    Plus,
    Trash2,
    UserRound,
    Video
} from 'lucide-angular'
import {MeetingApiService} from '../core/meeting-api.service'
import {MeetingStateService} from '../core/meeting-state.service'
import {CreateMeetingDto, ParticipantRole} from '../models/meeting.models'
import {DateTimePickerComponent} from '../shared/date-time-picker.component'
import {SessionsHeaderComponent} from '../shared/sessions-header.component'

const presets = [{label: 'HD (1280 × 720)', width: 1280, height: 720}, {
    label: 'Full HD (1920 × 1080)',
    width: 1920,
    height: 1080
}, {label: 'SD (854 × 480)', width: 854, height: 480}, {label: 'nHD (640 × 360)', width: 640, height: 360}]

@Component({
    selector: 'app-create-meeting-page',
    imports: [ReactiveFormsModule, DateTimePickerComponent, SessionsHeaderComponent, LucideAngularModule],
    template: `
        <div class="min-h-screen bg-page">
            <app-sessions-header/>
            <main class="mx-auto w-full max-w-[632px] px-5 py-9 pb-14">
                <h1 class="text-2xl font-semibold tracking-tight text-white">New Meeting</h1>
                <p class="mt-2 text-sm text-muted">Configure your meeting settings and participants.</p>

                <form [formGroup]="form" (ngSubmit)="submit()" class="mt-8 space-y-7">
                    <section class="session-card p-5"><h2 class="section-label border-b border-[#1c293d] pb-3">Basic
                        info</h2><label class="mt-4 block"><span class="field-label">Title</span><input
                            formControlName="title" class="field-control" placeholder="Q3 Product Review"></label>
                    </section>
                    <section class="session-card p-5"><h2 class="section-label border-b border-[#1c293d] pb-3">
                        Schedule</h2>
                        <div class="mt-4 grid gap-4 sm:grid-cols-[1fr_120px]"><label><span class="field-label">Scheduled at</span>
                            <app-date-time-picker formControlName="scheduledAt"/>
                        </label><label><span class="field-label">Duration (minutes)</span><input type="number" min="1"
                                                                                                 max="480"
                                                                                                 formControlName="durationLimitMinutes"
                                                                                                 class="field-control"></label>
                        </div>
                    </section>
                    <section class="session-card space-y-4 p-5"><h2
                            class="section-label border-b border-[#1c293d] pb-3">Connection</h2><label><span
                            class="field-label">Join Base URL</span><input formControlName="joinBaseUrl"
                                                                           class="field-control"></label><label><span
                            class="field-label">Callback URL</span><input formControlName="callbackUrl"
                                                                          class="field-control"
                                                                          placeholder="https://api.example.com/webhooks/meeting"></label>
                    </section>
                    <section class="session-card p-5">
                        <div class="flex items-center justify-between border-b border-[#1c293d] pb-3"><h2
                                class="section-label">Additional Metadata (optional)</h2><label
                                class="flex cursor-pointer items-center gap-1 text-xs text-[#86a5d2]">
                            <lucide-icon [img]="FileUp" class="size-3.5"/>
                            Import JSON<input type="file" accept="application/json,.json" class="hidden"
                                              (change)="importJson($event)"></label></div>
                        <label class="mt-4 block"><span class="field-label">JSON Payload</span><textarea
                                formControlName="metadata" rows="4" class="field-control resize-y font-mono text-xs"
                                placeholder='{"department":"engineering"}'></textarea></label></section>
                    <section class="session-card p-5">
                        <div class="flex items-center justify-between border-b border-[#1c293d] pb-3"><h2
                                class="section-label">Participants</h2>
                            <button type="button" class="text-xs text-[#86a5d2] hover:text-white"
                                    (click)="addParticipant()">
                                <lucide-icon [img]="Plus" class="mr-1 inline size-3.5"/>
                                Add participant
                            </button>
                        </div>
                        <div formArrayName="participants"
                             class="mt-4 space-y-2">@for (participant of participants.controls; track $index) {
                            <div [formGroupName]="$index"
                                 class="grid grid-cols-[34px_minmax(0,1fr)_72px_24px] items-center gap-2"><span
                                    class="grid size-7 place-items-center rounded-full border border-brand/40 bg-brand/10 text-[10px] font-semibold text-[#83b2ff]">{{ initials(participant.value.name) }}</span><input
                                    formControlName="name" class="field-control py-2" placeholder="Participant name">
                                <button type="button" (click)="makeHost($index)"
                                        class="rounded-md border px-2 py-2 text-[10px] font-bold"
                                        [class.border-amber]="participant.value.role === 'host'"
                                        [class.text-amber]="participant.value.role === 'host'"
                                        [class.border-line]="participant.value.role !== 'host'"
                                        [class.text-muted]="participant.value.role !== 'host'">♛ HOST
                                </button>
                                <button type="button" [disabled]="participants.length <= 2"
                                        (click)="removeParticipant($index)"
                                        class="text-muted hover:text-danger disabled:opacity-30">
                                    <lucide-icon [img]="Trash2" class="size-4"/>
                                </button>
                            </div>
                        }</div>
                    </section>
                    <section class="session-card p-5"><h2 class="section-label border-b border-[#1c293d] pb-3">
                        Recording</h2>
                        <div class="mt-4 flex items-center justify-between"><span class="text-sm text-[#9eb4d5]">Enable recording</span>
                            <button type="button" (click)="toggleRecording()"
                                    class="relative h-6 w-11 rounded-full transition"
                                    [class.bg-brand]="recordingEnabled" [class.bg-[#263653]]="!recordingEnabled"><span
                                    class="absolute top-1 size-4 rounded-full bg-white transition"
                                    [class.left-1]="!recordingEnabled" [class.left-6]="recordingEnabled"></span>
                            </button>
                        </div>@if (recordingEnabled) {
                            <div class="mt-4 grid gap-3 sm:grid-cols-3"><label class="sm:col-span-3"><span
                                    class="field-label">Resolution preset</span><select class="field-control"
                                                                                        (change)="selectPreset($event)">@for (preset of presets; track preset.label) {
                                <option [value]="preset.width + 'x' + preset.height">{{ preset.label }}</option>
                            }
                                <option value="custom">Custom</option>
                            </select></label><label><span class="field-label">Width</span><input type="number"
                                                                                                 formControlName="recordingWidth"
                                                                                                 class="field-control"></label><label><span
                                    class="field-label">Height</span><input type="number"
                                                                            formControlName="recordingHeight"
                                                                            class="field-control"></label>
                                <div class="flex items-end">
                                    <lucide-icon [img]="Monitor" class="mb-3 size-5 text-muted"/>
                                    <span class="mb-3 ml-2 text-xs text-muted">MP4</span></div>
                            </div>
                        }</section>
                    @if (error()) {
                        <p class="rounded-lg border border-danger/40 bg-danger/10 px-3 py-2 text-sm text-[#ff9fa7]">{{ error() }}</p>
                    }
                    <button type="submit" [disabled]="loading()"
                            class="btn-primary w-full">{{ loading() ? 'Creating…' : 'Create Meeting' }}
                    </button>
                </form>
            </main>
        </div>
    `
})
export class CreateMeetingPageComponent {
    private readonly fb = inject(FormBuilder);
    private readonly api = inject(MeetingApiService);
    private readonly state = inject(MeetingStateService);
    private readonly router = inject(Router)
    readonly loading = signal(false);
    readonly error = signal('');
    readonly presets = presets
    readonly form = this.fb.group({
        title: ['', [Validators.required, Validators.maxLength(200)]],
        scheduledAt: ['', Validators.required],
        durationLimitMinutes: [60, [Validators.required, Validators.min(1), Validators.max(480)]],
        joinBaseUrl: [window.location.origin, Validators.required],
        callbackUrl: ['', Validators.required],
        metadata: [''],
        recordingWidth: [1280, [Validators.min(1)]],
        recordingHeight: [720, [Validators.min(1)]],
        participants: this.fb.array([this.participant('host'), this.participant('guest'), this.participant('guest')])
    })
    recordingEnabled = false
    protected readonly FileUp = FileUp;
    protected readonly Plus = Plus;
    protected readonly Trash2 = Trash2;
    protected readonly Monitor = Monitor

    get participants(): FormArray {
        return this.form.controls.participants
    }

    private participant(role: ParticipantRole) {
        return this.fb.group({name: ['', Validators.required], role: [role]})
    }

    initials(value: string | null | undefined): string {
        return value?.trim().split(/\s+/).map(part => part[0]).join('').slice(0, 2).toUpperCase() || '…'
    }

    addParticipant(): void {
        if (this.participants.length < 6) this.participants.push(this.participant('guest'))
    }

    removeParticipant(index: number): void {
        if (this.participants.length > 2) {
            this.participants.removeAt(index);
            if (!this.participants.controls.some(item => item.value.role === 'host')) this.makeHost(0)
        }
    }

    makeHost(index: number): void {
        this.participants.controls.forEach((item, itemIndex) => item.get('role')?.setValue(itemIndex === index ? 'host' : 'guest'))
    }

    toggleRecording(): void {
        this.recordingEnabled = !this.recordingEnabled
    }

    selectPreset(event: Event): void {
        const value = (event.target as HTMLSelectElement).value;
        if (value === 'custom') return;
        const [width, height] = value.split('x').map(Number);
        this.form.controls.recordingWidth.setValue(width);
        this.form.controls.recordingHeight.setValue(height)
    }

    importJson(event: Event): void {
        const file = (event.target as HTMLInputElement).files?.[0];
        if (!file) return;
        file.text().then(text => {
            JSON.parse(text);
            this.form.controls.metadata.setValue(JSON.stringify(JSON.parse(text), null, 2));
            this.error.set('')
        }).catch(() => this.error.set('The selected file is not valid JSON.'))
    }

    submit(): void {
        this.error.set('');
        this.form.markAllAsTouched();
        const data = this.form.getRawValue();
        const participants = data.participants.map(item => ({
            name: item.name?.trim() ?? '',
            role: item.role as ParticipantRole
        }));
        const hostCount = participants.filter(item => item.role === 'host').length
        if (this.form.invalid || hostCount !== 1 || participants.some(item => !item.name) || !this.absoluteUrl(data.joinBaseUrl) || !this.absoluteUrl(data.callbackUrl)) {
            this.error.set('Complete all required fields with a future date, valid URLs, and exactly one host.');
            return
        }
        const scheduledAt = new Date(data.scheduledAt as string);
        if (Number.isNaN(scheduledAt.getTime()) || scheduledAt <= new Date()) {
            this.error.set('Scheduled date and time must be in the future.');
            return
        }
        let metadata: unknown = null;
        const rawMetadata = data.metadata?.trim() ?? '';
        if (rawMetadata) {
            try {
                metadata = JSON.parse(rawMetadata)
            } catch {
                metadata = rawMetadata
            }
        }
        const dto: CreateMeetingDto = {
            title: data.title?.trim() ?? '',
            scheduledAt: scheduledAt.toISOString(),
            durationLimitMinutes: Number(data.durationLimitMinutes),
            participants,
            recording: {
                enabled: this.recordingEnabled,
                format: 'mp4',
                width: this.even(Number(data.recordingWidth)),
                height: this.even(Number(data.recordingHeight))
            },
            callbackUrl: data.callbackUrl?.trim() ?? '',
            joinBaseUrl: data.joinBaseUrl?.trim() ?? '',
            metadata
        }
        this.loading.set(true);
        this.api.createMeeting(dto).pipe(finalize(() => this.loading.set(false))).subscribe({
            next: result => {
                this.state.setCreated(result);
                this.router.navigateByUrl('/meeting-created')
            }, error: error => this.error.set(error.error?.message || error.message || 'Meeting could not be created.')
        })
    }

    private absoluteUrl(value: string | null): boolean {
        try {
            const url = new URL(value ?? '');
            return Boolean(url.protocol && url.host)
        } catch {
            return false
        }
    }

    private even(value: number): number {
        return Math.max(2, Math.floor(value / 2) * 2)
    }
}

// web/src/pages/CreateMeetingPage.tsx
import React, {useState} from 'react'
import {useNavigate} from 'react-router-dom'
import {Plus, Trash2, Video, Users, Link, Clock, Webhook, FileJson, Crown, Monitor} from 'lucide-react'
import {createMeeting} from '../api/MeetingApi.ts'
import type {CreateParticipantDto} from '../types'
import {useMountTransition} from '../hooks/useMountTransition'
import {DateTimePicker} from '../components/DateTimePicker'
import {FormErrors, ParticipantRowProps} from '../types/pages.ts'
import {RESOLUTION_PRESETS, CUSTOM_RESOLUTION} from "../constants/constants.ts";


function validate(fields: {
    title: string; scheduledAt: string; durationLimitMinutes: string
    joinBaseUrl: string; callbackUrl: string; participants: CreateParticipantDto[]
    recordingWidth: string; recordingHeight: string
}): FormErrors {
    const errors: FormErrors = {}
    const urlRegex = /^https?:\/\/.+/
    if (!fields.title.trim()) errors.title = 'Title is required.'
    if (!fields.scheduledAt) errors.scheduledAt = 'Please select a date and time.'
    const duration = Number(fields.durationLimitMinutes)
    if (!fields.durationLimitMinutes || isNaN(duration) || duration < 1) errors.durationLimitMinutes = 'Enter a valid duration (min 1 minute).'
    if (!fields.joinBaseUrl.trim()) errors.joinBaseUrl = 'Join base URL is required.'
    else if (!urlRegex.test(fields.joinBaseUrl.trim())) errors.joinBaseUrl = 'Must start with http:// or https://'
    if (fields.callbackUrl.trim() && !urlRegex.test(fields.callbackUrl.trim())) errors.callbackUrl = 'Must start with http:// or https://'
    const recordingWidth = Number(fields.recordingWidth)
    const recordingHeight = Number(fields.recordingHeight)
    if (!fields.recordingWidth || isNaN(recordingWidth) || recordingWidth < 1) errors.recordingWidth = 'Enter a valid width.'
    if (!fields.recordingHeight || isNaN(recordingHeight) || recordingHeight < 1) errors.recordingHeight = 'Enter a valid height.'
    if (fields.participants.length === 0) errors.participants = 'Add at least one participant.'
    else if (!fields.participants.some(p => p.role === 'host')) errors.participants = 'At least one participant must be a host.'
    const participantNames: Record<number, string> = {}
    fields.participants.forEach((p, i) => {
        if (!p.name.trim()) participantNames[i] = 'Name is required.'
    })
    if (Object.keys(participantNames).length > 0) errors.participantNames = participantNames
    return errors
}

function getPresetValue(width: string, height: string) {
    const match = RESOLUTION_PRESETS.find(p => String(p.width) === width && String(p.height) === height)
    return match?.value ?? CUSTOM_RESOLUTION
}

function sanitizeDimensionInput(value: string) {
    return value.replace(/\D/g, '').slice(0, 5)
}

function ParticipantRow({index, participant, onChange, onRemove, nameError, canRemove}: ParticipantRowProps) {
    const isHost = participant.role === 'host'

    return (
        <div className="grid grid-cols-[minmax(0,1fr)_auto_auto] gap-3 items-center">
            <div className="min-w-0">
                <input
                    type="text"
                    value={participant.name}
                    onChange={e => onChange(index, 'name', e.target.value)}
                    placeholder="Full name"
                    onFocus={(e) => e.target.select()}
                    className={`w-full bg-transparent text-text-primary text-sm outline-none placeholder:text-text-secondary border-b pb-0.5 transition-colors ${nameError ? 'border-text-error' : 'border-border focus:border-brand'}`}
                />
                <p className={`text-text-error text-xs mt-0.5 h-3.5 ${nameError ? 'visible' : 'invisible'}`}>{nameError ?? ''}</p>
            </div>

            <button
                onClick={() => !isHost && onChange(index, 'role', 'host')}
                disabled={isHost}
                className={`
                    flex items-center justify-center gap-1.5 w-20 py-1 rounded-lg border text-xs
                    transition-all duration-150 flex-shrink-0
                    ${isHost
                    ? 'bg-brand-muted border-brand text-brand cursor-default'
                    : 'bg-transparent border-border text-text-secondary hover:border-brand/50 hover:text-text-primary'
                }
                `}
            >
                <Crown className={`w-3 h-3 transition-colors ${isHost ? 'text-brand' : 'text-text-secondary'}`}/>
                Host
            </button>

            <div className="w-3.5 flex justify-center">
                {canRemove && (
                    <button
                        onClick={() => onRemove(index)}
                        className="text-text-secondary hover:text-text-error transition-colors flex-shrink-0 mb-1"
                    >
                        <Trash2 className="w-3.5 h-3.5"/>
                    </button>
                )}
            </div>
        </div>
    )
}

function Field({icon, label, error, children}: {
    icon: React.ReactNode; label: string; error?: string; children: React.ReactNode
}) {
    return (
        <div
            className={`h-[72px] flex items-center gap-2.5 px-3 py-2.5 rounded-xl bg-surface border transition-colors ${error ? 'border-text-error' : 'border-border'}`}>
            <div
                className="w-8 h-8 rounded-lg bg-brand-muted flex items-center justify-center flex-shrink-0">{icon}</div>
            <div className="flex-1 min-w-0">
                <div className="text-xs text-text-secondary">{label}</div>
                {children}
                <p className={`text-text-error text-xs h-3.5 ${error ? 'visible' : 'invisible'}`}>{error ?? ''}</p>
            </div>
        </div>
    )
}

function RecordingSettingField({label, error, children, disabled}: {
    label: string; error?: string; children: React.ReactNode; disabled?: boolean
}) {
    return (
        <div
            className={`min-h-[72px] px-3 py-2.5 rounded-xl bg-page/20 border transition-colors ${disabled ? 'opacity-60' : ''} ${error ? 'border-text-error' : 'border-border'}`}>
            <div className="text-xs text-text-secondary">{label}</div>
            {children}
            <p className={`text-text-error text-xs h-3.5 ${error ? 'visible' : 'invisible'}`}>{error ?? ''}</p>
        </div>
    )
}

export function CreateMeetingPage() {
    const navigate = useNavigate()
    const mounted = useMountTransition()
    const [title, setTitle] = useState('')
    const [scheduledAt, setScheduledAt] = useState('')
    const [durationLimitMinutes, setDurationLimitMinutes] = useState('60')
    const [joinBaseUrl, setJoinBaseUrl] = useState(window.location.origin)
    const [callbackUrl, setCallbackUrl] = useState('')
    const [metadata, setMetadata] = useState('')
    const [recordingEnabled, setRecordingEnabled] = useState(false)
    const [recordingWidth, setRecordingWidth] = useState('1280')
    const [recordingHeight, setRecordingHeight] = useState('720')
    const [resolutionPreset, setResolutionPreset] = useState('1280x720')
    const [participants, setParticipants] = useState<CreateParticipantDto[]>([
        {name: '', role: 'host'}, {name: '', role: 'guest'}, {name: '', role: 'guest'},
    ])
    const [errors, setErrors] = useState<FormErrors>({})
    const [isLoading, setIsLoading] = useState(false)
    const [apiError, setApiError] = useState<string | null>(null)

    function handleParticipantChange(index: number, field: keyof CreateParticipantDto, value: string) {
        setParticipants(prev => prev.map((p, i) => {
            if (i === index) return {...p, [field]: value}
            if (field === 'role' && value === 'host') return {...p, role: 'guest'}
            return p
        }))
    }

    function handleResolutionPresetChange(value: string) {
        setResolutionPreset(value)
        if (value === CUSTOM_RESOLUTION) return

        const selectedPreset = RESOLUTION_PRESETS.find(p => p.value === value)
        if (!selectedPreset) return

        setRecordingWidth(String(selectedPreset.width))
        setRecordingHeight(String(selectedPreset.height))
    }

    function handleRecordingDimensionChange(field: 'width' | 'height', value: string) {
        const sanitizedValue = sanitizeDimensionInput(value)
        const nextWidth = field === 'width' ? sanitizedValue : recordingWidth
        const nextHeight = field === 'height' ? sanitizedValue : recordingHeight

        if (field === 'width') setRecordingWidth(sanitizedValue)
        else setRecordingHeight(sanitizedValue)

        setResolutionPreset(getPresetValue(nextWidth, nextHeight))
    }

    async function handleSubmit() {
        const validationErrors = validate({
            title,
            scheduledAt,
            durationLimitMinutes,
            joinBaseUrl,
            callbackUrl,
            participants,
            recordingWidth,
            recordingHeight
        })
        if (Object.keys(validationErrors).length > 0) {
            setErrors(validationErrors);
            return
        }
        setErrors({});
        setApiError(null);
        setIsLoading(true)
        try {
            const response = await createMeeting({
                title: title.trim(),
                scheduledAt: new Date(scheduledAt).toISOString(),
                durationLimitMinutes: Number(durationLimitMinutes),
                participants,
                recording: {
                    enabled: recordingEnabled,
                    format: 'mp4',
                    width: Math.floor(Number(recordingWidth) / 2) * 2,
                    height: Math.floor(Number(recordingHeight) / 2) * 2,
                },
                callbackUrl: callbackUrl.trim(),
                joinBaseUrl: joinBaseUrl.trim(),
                metadata: metadata.trim(),
            })
            navigate('/meeting-created', {state: {result: response}})
        } catch (e) {
            setApiError((e as Error).message)
        } finally {
            setIsLoading(false)
        }
    }

    return (
        <div className="min-h-screen flex items-center justify-center bg-page p-4">
            <div
                className={`max-w-2xl w-full transition-all duration-500 ${mounted ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-5'}`}>
                <div className="text-center mb-4">
                    <h1 className="text-2xl text-text-primary mb-1">New Meeting</h1>
                    <p className="text-text-secondary text-sm">Set up your meeting and get join links for all
                        participants.</p>
                </div>
                <div className="space-y-2">

                    <Field icon={<Video className="w-4 h-4 text-brand"/>} label="Meeting title" error={errors.title}>
                        <input type="text" value={title} onChange={e => setTitle(e.target.value)}
                               placeholder="Weekly sync, design review..."
                               className="w-full bg-transparent text-text-primary text-sm outline-none placeholder:text-text-secondary"/>
                    </Field>

                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                        <DateTimePicker value={scheduledAt} onChange={setScheduledAt} error={errors.scheduledAt}/>
                        <Field icon={<Clock className="w-4 h-4 text-brand"/>} label="Duration (minutes)"
                               error={errors.durationLimitMinutes}>
                            <input type="number" value={durationLimitMinutes}
                                   onChange={e => setDurationLimitMinutes(e.target.value)}
                                   className="w-full bg-transparent text-text-primary text-sm outline-none"/>
                        </Field>
                    </div>

                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                        <Field icon={<Link className="w-4 h-4 text-brand"/>} label="Join base URL"
                               error={errors.joinBaseUrl}>
                            <input type="text" value={joinBaseUrl} onChange={e => setJoinBaseUrl(e.target.value)}
                                   className="w-full bg-transparent text-text-primary text-sm outline-none"/>
                        </Field>
                        <Field icon={<Webhook className="w-4 h-4 text-brand"/>} label="Callback URL (optional)"
                               error={errors.callbackUrl}>
                            <input type="text" value={callbackUrl} onChange={e => setCallbackUrl(e.target.value)}
                                   placeholder="https://webhook.site/..."
                                   className="w-full bg-transparent text-text-primary text-sm outline-none"/>
                        </Field>
                    </div>

                    <Field icon={<FileJson className="w-4 h-4 text-brand"/>} label="Additional Metadata (optional)">
                        <input type="text" value={metadata} onChange={e => setMetadata(e.target.value)}
                               placeholder="Meeting tags, external IDs..."
                               className="w-full bg-transparent text-text-primary text-sm outline-none"/>
                    </Field>

                    <div
                        className={`px-3 py-2.5 rounded-xl bg-surface border ${errors.participants ? 'border-text-error' : 'border-border'}`}>
                        <div
                            className="grid grid-cols-[minmax(0,1fr)_auto_auto] gap-3 items-center mb-2 pr-2 overflow-y-auto"
                            style={{scrollbarGutter: 'stable'}}
                        >
                            <div className="flex items-center gap-2">
                                <div className="w-8 h-8 rounded-lg bg-brand-muted flex items-center justify-center">
                                    <Users className="w-4 h-4 text-brand"/>
                                </div>
                                <div>
                                    <div className="text-text-primary text-sm font-medium">Participants</div>
                                    <div className="text-text-secondary text-xs">A meeting can have exactly one host
                                    </div>
                                </div>
                            </div>
                            <button
                                onClick={() => setParticipants(prev => [...prev, {name: '', role: 'guest'}])}
                                className="flex items-center justify-center gap-1 w-20 py-1 rounded-lg bg-brand-muted border border-brand text-brand text-xs transition-transform duration-150 hover:scale-[1.03] active:scale-[0.97]"
                            >
                                <Plus className="w-3.5 h-3.5"/> Add
                            </button>
                            <div className="w-3.5" aria-hidden="true"/>
                        </div>
                        <p className={`text-text-error text-xs h-3.5 mb-1 ${errors.participants ? 'visible' : 'invisible'}`}>{errors.participants ?? ''}</p>
                        <div
                            className="space-y-2 overflow-y-auto pr-2 custom-scrollbar"
                            style={{height: '150px', scrollbarGutter: 'stable'}}
                        >
                            {participants.map((p, i) => (
                                <ParticipantRow
                                    key={i} index={i} participant={p}
                                    onChange={handleParticipantChange}
                                    onRemove={idx => {
                                        const isRemovingHost = participants[idx].role === 'host'
                                        const newParticipants = participants.filter((_, j) => j !== idx)
                                        if (isRemovingHost && newParticipants.length > 0) newParticipants[0].role = 'host'
                                        setParticipants(newParticipants)
                                    }}
                                    nameError={errors.participantNames?.[i]}
                                    canRemove={participants.length > 1}
                                />
                            ))}
                        </div>
                    </div>

                    <div className="flex items-center gap-3 p-4 rounded-xl bg-surface border border-border">
                        <div
                            className="w-10 h-10 rounded-lg bg-brand-muted flex items-center justify-center flex-shrink-0">
                            <span
                                className={`w-2.5 h-2.5 rounded-full transition-colors ${recordingEnabled ? 'bg-text-error animate-pulse' : 'bg-text-secondary'}`}/>
                        </div>
                        <div className="flex-1">
                            <div className="text-text-primary text-sm font-medium">Recording</div>
                            <div className="text-text-secondary text-xs">Save this meeting as an MP4</div>
                        </div>
                        <button
                            onClick={() => setRecordingEnabled(r => !r)}
                            className={`relative w-12 h-6 rounded-full p-0.5 transition-colors duration-200 flex items-center ${recordingEnabled ? 'bg-brand' : 'bg-surface border border-border'}`}
                        >
                            <span
                                className={`w-5 h-5 rounded-full bg-text-primary shadow transition-transform duration-200 ${recordingEnabled ? 'translate-x-6' : 'translate-x-0'}`}/>
                        </button>
                    </div>

                    <div className="rounded-xl bg-surface border border-border p-3">
                        <div className="flex items-center gap-2 mb-3">
                            <div
                                className="w-8 h-8 rounded-lg bg-brand-muted flex items-center justify-center flex-shrink-0">
                                <Monitor className="w-4 h-4 text-brand"/>
                            </div>
                            <div>
                                <div className="text-text-primary text-sm font-medium">Recording resolution</div>
                                <div className="text-text-secondary text-xs">Choose a preset or fine-tune width and
                                    height.
                                </div>
                            </div>
                        </div>
                        <div className="grid grid-cols-1 sm:grid-cols-[minmax(0,1.4fr)_1fr_1fr] gap-2">
                            <RecordingSettingField label="Preset" disabled={!recordingEnabled}>
                                <select
                                    value={resolutionPreset}
                                    onChange={e => handleResolutionPresetChange(e.target.value)}
                                    disabled={!recordingEnabled}
                                    className="w-full bg-transparent text-text-primary text-sm outline-none disabled:cursor-not-allowed"
                                >
                                    {RESOLUTION_PRESETS.map(option => (
                                        <option key={option.value} value={option.value}
                                                className="bg-surface text-text-primary">
                                            {option.label}
                                        </option>
                                    ))}
                                    <option value={CUSTOM_RESOLUTION} className="bg-surface text-text-primary">
                                        Custom
                                    </option>
                                </select>
                            </RecordingSettingField>
                            <RecordingSettingField label="Width" error={errors.recordingWidth}
                                                   disabled={!recordingEnabled}>
                                <input
                                    type="text"
                                    inputMode="numeric"
                                    value={recordingWidth}
                                    onChange={e => handleRecordingDimensionChange('width', e.target.value)}
                                    disabled={!recordingEnabled}
                                    placeholder="1280"
                                    className="w-full bg-transparent text-text-primary text-sm outline-none placeholder:text-text-secondary disabled:cursor-not-allowed"
                                />
                            </RecordingSettingField>
                            <RecordingSettingField label="Height" error={errors.recordingHeight}
                                                   disabled={!recordingEnabled}>
                                <input
                                    type="text"
                                    inputMode="numeric"
                                    value={recordingHeight}
                                    onChange={e => handleRecordingDimensionChange('height', e.target.value)}
                                    disabled={!recordingEnabled}
                                    placeholder="720"
                                    className="w-full bg-transparent text-text-primary text-sm outline-none placeholder:text-text-secondary disabled:cursor-not-allowed"
                                />
                            </RecordingSettingField>
                        </div>
                    </div>

                    {apiError && <p className="text-text-error text-xs text-center">{apiError}</p>}

                    <button
                        onClick={handleSubmit}
                        disabled={isLoading}
                        className="w-full py-3 rounded-xl text-text-primary bg-brand shadow-brand-glow text-sm transition-transform duration-150 hover:scale-[1.02] active:scale-[0.98] disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        {isLoading ? 'Creating...' : 'Create Meeting'}
                    </button>
                </div>
            </div>
        </div>
    )
}
