// web-angular/src/app/pages/meeting-created-page.component.ts
import {Component, inject} from '@angular/core'
import {Router, RouterLink} from '@angular/router'
import {Check, Copy, ExternalLink, LucideAngularModule, Users, Video} from 'lucide-angular'
import {MeetingStateService} from '../core/meeting-state.service'
import {SessionsHeaderComponent} from '../shared/sessions-header.component'

@Component({
    selector: 'app-meeting-created-page',
    imports: [RouterLink, SessionsHeaderComponent, LucideAngularModule],
    template: `
        <div class="min-h-screen bg-page">
            <app-sessions-header/>
            @if (meeting(); as result) {
                <main class="mx-auto w-full max-w-[632px] px-5 py-12">
                    <div class="text-center"><span
                            class="mx-auto grid size-14 place-items-center rounded-full border-2 border-success bg-success/10"><lucide-icon
                            [img]="Check" class="size-7 text-success"/></span>
                        <h1 class="mt-4 text-2xl font-semibold text-slate-900">Meeting Created</h1>
                        <p class="mt-2 text-sm text-muted">Share the join links below with your participants.</p></div>
                    <section class="session-card mt-8 p-5">
                        <div class="flex items-center gap-3 border-b border-line pb-4">
                            <lucide-icon [img]="Video" class="size-5 text-brand"/>
                            <div><p class="text-xs text-muted">Meeting title</p>
                                <p class="mt-1 text-sm font-semibold text-slate-900">{{ result.title }}</p></div>
                        </div>
                        <div class="mt-4 flex gap-5 text-xs text-slate-500"><span class="flex items-center gap-1"><lucide-icon
                                [img]="Users" class="size-4"/>
                            {{ result.participants.length }} participants</span>@if (result.recordingEnabled) {
                            <span class="flex items-center gap-1"><i class="size-2 rounded-full bg-danger"></i>Recording enabled</span>
                        }</div>
                    </section>
                    <section class="mt-4 space-y-2">@for (participant of result.participants; track participant.id) {
                        <article class="session-card flex items-center gap-3 border-l-4 border-l-blue-400 p-3"><span
                                class="grid size-9 place-items-center rounded-full border border-brand/40 bg-blue-100 text-xs font-semibold text-blue-700">{{ initials(participant.name) }}</span>
                            <div class="min-w-0 flex-1"><p
                                    class="text-sm font-semibold text-slate-900">{{ participant.name }} @if (participant.role === 'host') {
                                <small class="ml-1 rounded border border-amber/50 px-1 py-0.5 text-[9px] text-amber">HOST</small>
                            }</p>
                                <p class="mt-1 truncate text-xs text-muted">{{ participant.joinLink }}</p></div>
                            <a [href]="participant.joinLink" target="_blank" rel="noreferrer"
                               class="rounded-lg p-2 text-slate-500 transition hover:bg-blue-50 hover:text-brand"
                               [attr.aria-label]="'Open link for ' + participant.name">
                                <lucide-icon [img]="ExternalLink" class="size-4"/>
                            </a>
                            <button (click)="copy(participant.joinLink)" class="rounded-lg p-2 text-slate-500 transition hover:bg-blue-50 hover:text-brand"
                                    [attr.aria-label]="'Copy link for ' + participant.name">
                                <lucide-icon [img]="Copy" class="size-4"/>
                            </button>
                        </article>
                    }</section>
                    <p class="mt-3 h-5 text-center text-xs text-success">{{ copied }}</p><a routerLink="/"
                                                                                            class="btn-secondary mt-3 w-full">Create
                    Another Meeting</a>
                </main>
            } @else {
                <main class="grid min-h-[calc(100vh-51px)] place-items-center p-6 text-center">
                    <div><p class="text-lg text-slate-900">No meeting result is available.</p><a routerLink="/"
                                                                                             class="btn-primary mt-5">Create
                        a meeting</a></div>
                </main>
            }
        </div>
    `
})
export class MeetingCreatedPageComponent {
    private readonly state = inject(MeetingStateService);
    protected readonly meeting = this.state.created;
    copied = ''
    protected readonly Check = Check;
    protected readonly Copy = Copy;
    protected readonly ExternalLink = ExternalLink;
    protected readonly Users = Users;
    protected readonly Video = Video

    initials(value: string): string {
        return value.split(/\s+/).map(part => part[0]).join('').slice(0, 2).toUpperCase()
    }

    copy(value: string): void {
        navigator.clipboard.writeText(value).then(() => {
            this.copied = 'Join link copied';
            setTimeout(() => this.copied = '', 2000)
        })
    }
}

// web/src/pages/MeetingCreatedPage.tsx
import {Key, useState} from 'react'
import {useNavigate, useLocation} from 'react-router-dom'
import {Copy, Check, Video, Users, ExternalLink} from 'lucide-react'
import type {CreateMeetingResponse} from '../types'
import {useMountTransition} from '../hooks/useMountTransition'

function JoinLinkRow({name, role, joinLink}: { name: string; role: string; joinLink: string }) {
    const [copied, setCopied] = useState(false)
    const handleCopy = () => {
        navigator.clipboard.writeText(joinLink);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000)
    }
    return (
        <div className="flex items-center gap-3 p-3 rounded-xl bg-surface border border-border">
            <div className="w-8 h-8 rounded-full bg-avatar-gradient flex items-center justify-center flex-shrink-0">
                <span className="text-xs text-text-primary font-semibold">{name.slice(0, 2).toUpperCase()}</span>
            </div>
            <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-0.5">
                    <span className="text-text-primary text-sm font-medium">{name}</span>
                    {role && <span
                        className="text-text-secondary text-xs px-1.5 py-0.5 rounded-full bg-brand-muted border border-border">{role}</span>}
                </div>
                <p className="text-text-secondary text-xs truncate">{joinLink}</p>
            </div>
            <div className="flex items-center gap-2 flex-shrink-0">
                <a href={joinLink} target="_blank" rel="noopener noreferrer"
                   className="text-text-secondary hover:text-brand transition-colors">
                    <ExternalLink className="w-3.5 h-3.5"/>
                </a>
                <button onClick={handleCopy} className="text-text-secondary hover:text-brand transition-colors">
                    {copied ? <Check className="w-3.5 h-3.5 text-brand"/> : <Copy className="w-3.5 h-3.5"/>}
                </button>
            </div>
        </div>
    )
}

export function MeetingCreatedPage() {
    const navigate = useNavigate()
    const mounted = useMountTransition()
    const location = useLocation()
    const result = (location.state as { result: CreateMeetingResponse })?.result

    if (!result) {
        navigate('/')
        return null
    }

    return (
        <div className="min-h-screen flex items-center justify-center p-6 bg-page">
            <div
                className={`max-w-2xl w-full transition-all duration-500 ${mounted ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-5'}`}>
                <div className="text-center mb-6">
                    <div
                        className="inline-flex w-14 h-14 rounded-full bg-brand-muted border-2 border-brand items-center justify-center mb-3">
                        <Check className="w-7 h-7 text-brand"/>
                    </div>
                    <h1 className="text-2xl text-text-primary mb-1">Meeting Created</h1>
                    <p className="text-text-secondary text-sm">Share the join links below with your participants.</p>
                </div>

                <div className="rounded-2xl p-4 bg-surface border border-border mb-4">
                    <div className="flex items-center gap-3 mb-3 pb-3 border-b border-border">
                        <Video className="w-4 h-4 text-brand flex-shrink-0"/>
                        <div>
                            <p className="text-text-secondary text-xs">Meeting title</p>
                            <p className="text-text-primary text-sm font-medium">{result.title}</p>
                        </div>
                    </div>
                    <div className="flex items-center gap-4">
                        <div className="flex items-center gap-1.5">
                            <Users className="w-3.5 h-3.5 text-text-secondary"/>
                            <span
                                className="text-text-secondary text-xs">{result.participants.length} participants</span>
                        </div>
                        {result.recordingEnabled && (
                            <div className="flex items-center gap-1.5">
                                <span className="w-1.5 h-1.5 rounded-full bg-text-error animate-pulse"/>
                                <span className="text-text-secondary text-xs">Recording enabled</span>
                            </div>
                        )}
                    </div>
                </div>

                <div className="space-y-2 mb-4">
                    {result.participants.map((p: { id: Key; name: string; role: string; joinLink: string }) => (
                        <JoinLinkRow key={p.id as Key} name={p.name} role={p.role} joinLink={p.joinLink}/>
                    ))}
                </div>

                <button onClick={() => navigate('/')}
                        className="w-full py-3 rounded-xl text-text-primary bg-surface border border-border text-sm transition-transform duration-150 hover:scale-[1.02] active:scale-[0.98]">
                    Create Another Meeting
                </button>
            </div>
        </div>
    )
}
