// web-angular/src/app/shared/date-time-picker.component.ts
import {CommonModule} from '@angular/common'
import {Component, forwardRef, HostListener} from '@angular/core'
import {ControlValueAccessor, NG_VALUE_ACCESSOR} from '@angular/forms'
import {Calendar, ChevronLeft, ChevronRight, Clock, LucideAngularModule} from 'lucide-angular'

const monthFormatter = new Intl.DateTimeFormat('en-US', {month: 'long', year: 'numeric'})
const displayFormatter = new Intl.DateTimeFormat('en-US', {
    weekday: 'short', month: 'short', day: 'numeric', year: 'numeric'
})

type CalendarCell = number | null

@Component({
    selector: 'app-date-time-picker',
    standalone: true,
    imports: [CommonModule, LucideAngularModule],
    providers: [{provide: NG_VALUE_ACCESSOR, useExisting: forwardRef(() => DateTimePickerComponent), multi: true}],
    template: `
        <div class="relative">
            <button type="button" class="field-control flex items-center justify-between gap-3 text-left"
                    [class.border-brand]="open" [attr.aria-expanded]="open" aria-haspopup="dialog"
                    (click)="toggle()">
                <span class="min-w-0 truncate" [class.text-white]="selectedDate" [class.text-[#60718c]]="!selectedDate">
                    {{ selectedDate ? displayValue() : 'mm/dd/yyyy, --:--' }}
                </span>
                <lucide-icon [img]="Calendar" class="size-4 shrink-0 text-muted"/>
            </button>

            @if (open) {
                <div class="datetime-picker-panel absolute left-0 top-full z-50 mt-2 w-full min-w-[300px] rounded-xl border border-line bg-panel p-4 shadow-panel"
                     role="dialog" aria-label="Choose meeting date and time">
                    <div class="flex items-center justify-between">
                        <button type="button" class="picker-nav" aria-label="Previous month"
                                [disabled]="isPreviousMonthDisabled()" (click)="changeMonth(-1)">
                            <lucide-icon [img]="ChevronLeft" class="size-4"/>
                        </button>
                        <span class="text-sm font-semibold text-white">{{ monthLabel() }}</span>
                        <button type="button" class="picker-nav" aria-label="Next month" (click)="changeMonth(1)">
                            <lucide-icon [img]="ChevronRight" class="size-4"/>
                        </button>
                    </div>

                    <div class="mt-4 grid grid-cols-7 gap-1 text-center text-[10px] font-semibold uppercase tracking-wide text-muted">
                        @for (day of weekdays; track day) { <span>{{ day }}</span> }
                    </div>
                    <div class="mt-2 grid grid-cols-7 gap-1">
                        @for (day of calendarCells(); track $index) {
                            @if (day === null) {
                                <span class="size-8"></span>
                            } @else {
                                <button type="button" class="picker-day" [class.selected]="isSelectedDay(day)"
                                        [class.today]="isToday(day)" [disabled]="isDateDisabled(day)"
                                        (click)="selectDay(day)">{{ day }}</button>
                            }
                        }
                    </div>

                    <div class="mt-4 border-t border-line pt-3">
                        <div class="mb-2 flex items-center gap-2 text-xs font-medium text-muted">
                            <lucide-icon [img]="Clock" class="size-3.5 text-brand"/> Time
                        </div>
                        <div class="grid grid-cols-2 gap-2">
                            <label class="sr-only" for="meeting-hour">Hour</label>
                            <select id="meeting-hour" class="picker-select" [value]="hour"
                                    [disabled]="!selectedDate" (change)="selectHour($event)">
                                @for (item of hours; track item) {
                                    <option [value]="item" [disabled]="isHourDisabled(item)">{{ item }}</option>
                                }
                            </select>
                            <label class="sr-only" for="meeting-minute">Minute</label>
                            <select id="meeting-minute" class="picker-select" [value]="minute"
                                    [disabled]="!selectedDate" (change)="selectMinute($event)">
                                @for (item of minutes; track item) {
                                    <option [value]="item" [disabled]="isMinuteDisabled(item)">{{ item }}</option>
                                }
                            </select>
                        </div>
                    </div>

                    <button type="button" class="btn-primary mt-3 w-full py-2.5" [disabled]="!canConfirm()"
                            (click)="confirm()">Confirm</button>
                </div>
            }
        </div>
    `,
    styles: [`
        .datetime-picker-panel { background: #111a29; }
        .picker-nav { display: grid; place-items: center; width: 2rem; height: 2rem; border-radius: .5rem; border: 0; color: #8295b5; background: transparent; transition: background .15s, color .15s; }
        .picker-nav:hover:not(:disabled) { background: #1c293d; color: white; }
        .picker-nav:disabled { cursor: not-allowed; opacity: .3; }
        .picker-day { display: grid; place-items: center; width: 2rem; height: 2rem; border: 0; border-radius: .5rem; color: #b9c9e2; background: transparent; font-size: .75rem; transition: background .15s, color .15s; }
        .picker-day:hover:not(:disabled) { background: #1c293d; color: white; }
        .picker-day:disabled { cursor: not-allowed; color: #40506a; }
        .picker-day.today { border: 1px solid rgb(67 135 255 / .6); }
        .picker-day.selected { background: #397ef6; color: white; font-weight: 600; }
        .picker-day.selected:hover { background: #397ef6; }
        .picker-select { width: 100%; border: 1px solid #26354e; border-radius: .5rem; background: #172235; padding: .5rem .75rem; color: white; font-size: .875rem; outline: none; }
        .picker-select:focus { border-color: #397ef6; box-shadow: 0 0 0 2px rgb(57 126 246 / .2); }
        .picker-select:disabled { cursor: not-allowed; opacity: .4; }
    `]
})
export class DateTimePickerComponent implements ControlValueAccessor {
    readonly Calendar = Calendar
    readonly ChevronLeft = ChevronLeft
    readonly ChevronRight = ChevronRight
    readonly Clock = Clock
    readonly weekdays = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
    readonly hours = Array.from({length: 24}, (_, index) => this.pad(index))
    readonly minutes = Array.from({length: 60}, (_, index) => this.pad(index))

    open = false
    disabled = false
    selectedDate: Date | null = null
    viewDate = this.startOfDay(new Date())
    hour = this.pad(new Date().getHours())
    minute = this.pad(new Date().getMinutes())

    private onChange: (value: string) => void = () => undefined
    private onTouched: () => void = () => undefined

    @HostListener('document:mousedown', ['$event'])
    closeWhenClickedOutside(event: MouseEvent): void {
        if (this.open && event.target instanceof Node && !this.elementContains(event.target)) this.open = false
    }

    private elementContains(target: Node): boolean {
        return (target as HTMLElement).closest('app-date-time-picker') !== null
    }

    toggle(): void {
        if (this.disabled) return
        this.open = !this.open
        if (this.open) {
            this.onTouched()
            if (this.selectedDate) this.viewDate = this.startOfMonth(this.selectedDate)
            else this.viewDate = this.startOfMonth(new Date())
        }
    }

    monthLabel(): string {
        return monthFormatter.format(this.viewDate)
    }

    calendarCells(): CalendarCell[] {
        const firstDay = new Date(this.viewDate.getFullYear(), this.viewDate.getMonth(), 1).getDay()
        const daysInMonth = new Date(this.viewDate.getFullYear(), this.viewDate.getMonth() + 1, 0).getDate()
        return Array.from({length: firstDay + daysInMonth}, (_, index) => index < firstDay ? null : index - firstDay + 1)
    }

    changeMonth(offset: number): void {
        const next = new Date(this.viewDate.getFullYear(), this.viewDate.getMonth() + offset, 1)
        if (next < this.startOfMonth(new Date())) return
        this.viewDate = next
    }

    isPreviousMonthDisabled(): boolean {
        return this.viewDate.getFullYear() === new Date().getFullYear() && this.viewDate.getMonth() === new Date().getMonth()
    }

    isDateDisabled(day: number): boolean {
        return this.startOfDay(new Date(this.viewDate.getFullYear(), this.viewDate.getMonth(), day)) < this.startOfDay(new Date())
    }

    isToday(day: number): boolean {
        const today = new Date()
        return this.viewDate.getFullYear() === today.getFullYear() && this.viewDate.getMonth() === today.getMonth() && day === today.getDate()
    }

    isSelectedDay(day: number): boolean {
        return !!this.selectedDate && this.selectedDate.getFullYear() === this.viewDate.getFullYear() && this.selectedDate.getMonth() === this.viewDate.getMonth() && this.selectedDate.getDate() === day
    }

    selectDay(day: number): void {
        if (this.isDateDisabled(day)) return
        this.selectedDate = new Date(this.viewDate.getFullYear(), this.viewDate.getMonth(), day)
        this.ensureValidTime()
    }

    isHourDisabled(item: string): boolean {
        if (!this.selectedDate || !this.isTodayDate(this.selectedDate)) return false
        return Number(item) < new Date().getHours()
    }

    isMinuteDisabled(item: string): boolean {
        if (!this.selectedDate || !this.isTodayDate(this.selectedDate)) return false
        const current = new Date()
        return Number(this.hour) < current.getHours() || (Number(this.hour) === current.getHours() && Number(item) <= current.getMinutes())
    }

    selectHour(event: Event): void {
        const value = (event.target as HTMLSelectElement).value
        if (!this.isHourDisabled(value)) {
            this.hour = value
            this.ensureValidTime()
        }
    }

    selectMinute(event: Event): void {
        const value = (event.target as HTMLSelectElement).value
        if (!this.isMinuteDisabled(value)) this.minute = value
    }

    canConfirm(): boolean {
        return !!this.selectedDate && !this.isHourDisabled(this.hour) && !this.isMinuteDisabled(this.minute)
    }

    confirm(): void {
        if (!this.canConfirm() || !this.selectedDate) return
        this.onChange(this.toLocalValue())
        this.open = false
    }

    displayValue(): string {
        if (!this.selectedDate) return ''
        return `${displayFormatter.format(this.selectedDate)} · ${this.hour}:${this.minute}`
    }

    writeValue(value: string | null): void {
        if (!value) {
            this.selectedDate = null
            return
        }
        const parsed = new Date(value)
        if (Number.isNaN(parsed.getTime())) return
        this.selectedDate = this.startOfDay(parsed)
        this.viewDate = this.startOfMonth(parsed)
        this.hour = this.pad(parsed.getHours())
        this.minute = this.pad(parsed.getMinutes())
    }

    registerOnChange(fn: (value: string) => void): void { this.onChange = fn }
    registerOnTouched(fn: () => void): void { this.onTouched = fn }
    setDisabledState(isDisabled: boolean): void { this.disabled = isDisabled }

    private ensureValidTime(): void {
        if (!this.selectedDate || !this.isTodayDate(this.selectedDate)) return
        const now = new Date()
        if (Number(this.hour) < now.getHours()) this.hour = this.pad(now.getHours())
        if (Number(this.hour) === now.getHours() && Number(this.minute) <= now.getMinutes()) {
            this.minute = this.pad(Math.min(59, now.getMinutes() + 1))
            if (Number(this.minute) === 59 && now.getMinutes() === 59) this.hour = this.pad(now.getHours() + 1)
        }
    }

    private toLocalValue(): string {
        return `${this.selectedDate!.getFullYear()}-${this.pad(this.selectedDate!.getMonth() + 1)}-${this.pad(this.selectedDate!.getDate())}T${this.hour}:${this.minute}`
    }

    private isTodayDate(value: Date): boolean {
        const today = new Date()
        return value.getFullYear() === today.getFullYear() && value.getMonth() === today.getMonth() && value.getDate() === today.getDate()
    }

    private startOfDay(value: Date): Date { return new Date(value.getFullYear(), value.getMonth(), value.getDate()) }
    private startOfMonth(value: Date): Date { return new Date(value.getFullYear(), value.getMonth(), 1) }
    private pad(value: number): string { return String(value).padStart(2, '0') }
}

// web/src/components/DateTimePicker.tsx
import {useState, useRef, useEffect} from 'react'
import {createPortal} from 'react-dom'
import {Calendar, Clock, ChevronLeft, ChevronRight} from 'lucide-react'
import '../styles/datetimepicker.css'
import {DateTimePickerProps} from "../types/components.ts";
import {MONTHS, DAYS} from "../constants/constants.ts";
import {getDaysInMonth, getFirstDayOfMonth, pad} from "../utils/utils.ts";

function formatDisplay(value: string): string {
    if (!value) return ''
    const d = new Date(value)
    if (isNaN(d.getTime())) return ''
    return d.toLocaleDateString('en-US', {
        weekday: 'short', month: 'short', day: 'numeric', year: 'numeric',
    }) + ' · ' + pad(d.getHours()) + ':' + pad(d.getMinutes())
}

export function DateTimePicker({value, onChange, error}: DateTimePickerProps) {
    const [open, setOpen] = useState(false)
    const triggerRef = useRef<HTMLDivElement>(null)
    const dropdownRef = useRef<HTMLDivElement>(null)
    const minuteRef = useRef<HTMLInputElement>(null)
    const [pos, setPos] = useState({top: 0, left: 0})

    const parsed = value ? new Date(value) : null
    const today = new Date()

    const [viewYear, setViewYear] = useState(parsed?.getFullYear() ?? today.getFullYear())
    const [viewMonth, setViewMonth] = useState(parsed?.getMonth() ?? today.getMonth())
    const [selectedDate, setSelectedDate] = useState<{ y: number; m: number; d: number } | null>(
        parsed ? {y: parsed.getFullYear(), m: parsed.getMonth(), d: parsed.getDate()} : null
    )

    const [hour, setHour] = useState(parsed ? pad(parsed.getHours()) : pad(today.getHours()))
    const [minute, setMinute] = useState(parsed ? pad(parsed.getMinutes()) : pad(today.getMinutes()))

    useEffect(() => {
        if (!open || !triggerRef.current) return
        const r = triggerRef.current.getBoundingClientRect()
        setPos({top: r.bottom + window.scrollY + 8, left: r.left + window.scrollX})
    }, [open])

    useEffect(() => {
        function handle(e: MouseEvent) {
            if (
                triggerRef.current && !triggerRef.current.contains(e.target as Node) &&
                dropdownRef.current && !dropdownRef.current.contains(e.target as Node)
            ) setOpen(false)
        }

        document.addEventListener('mousedown', handle)
        return () => document.removeEventListener('mousedown', handle)
    }, [])

    useEffect(() => {
        if (!selectedDate) return
        const h = Math.min(23, Math.max(0, Number(hour) || 0))
        const m = Math.min(59, Math.max(0, Number(minute) || 0))
        onChange(`${selectedDate.y}-${pad(selectedDate.m + 1)}-${pad(selectedDate.d)}T${pad(h)}:${pad(m)}`)
    }, [selectedDate, hour, minute])

    const daysInMonth = getDaysInMonth(viewYear, viewMonth)
    const firstDay = getFirstDayOfMonth(viewYear, viewMonth)
    const cells = Array.from({length: firstDay + daysInMonth}, (_, i) => i < firstDay ? null : i - firstDay + 1)

    const isSelected = (d: number) => selectedDate?.y === viewYear && selectedDate?.m === viewMonth && selectedDate?.d === d
    const isToday = (d: number) => today.getFullYear() === viewYear && today.getMonth() === viewMonth && today.getDate() === d

    const dropdown = (
        <div
            ref={dropdownRef}
            className="datetimepicker-portal w-80 rounded-2xl overflow-hidden bg-[rgba(15,18,28,0.92)] backdrop-blur-[40px] border border-white/[0.12] shadow-[0_8px_48px_rgba(0,0,0,0.7)]"
            style={{top: pos.top, left: pos.left}}
        >
            <div className="flex items-center justify-between px-4 py-3 border-b border-white/[0.08]">
                <button
                    onClick={() => viewMonth === 0 ? (setViewMonth(11), setViewYear(y => y - 1)) : setViewMonth(m => m - 1)}
                    className="p-1 rounded-lg bg-white/[0.05] text-text-secondary hover:text-text-primary"><ChevronLeft
                    className="w-4 h-4"/></button>
                <span className="text-text-primary text-sm font-semibold">{MONTHS[viewMonth]} {viewYear}</span>
                <button
                    onClick={() => viewMonth === 11 ? (setViewMonth(0), setViewYear(y => y + 1)) : setViewMonth(m => m + 1)}
                    className="p-1 rounded-lg bg-white/[0.05] text-text-secondary hover:text-text-primary"><ChevronRight
                    className="w-4 h-4"/></button>
            </div>
            <div className="grid grid-cols-7 px-3 pt-3 pb-1">{DAYS.map(d => <div key={d}
                                                                                 className="text-center text-xs text-text-secondary py-1 font-medium">{d}</div>)}</div>
            <div className="grid grid-cols-7 px-3 pb-3 gap-y-1">
                {cells.map((d, i) => (
                    <div key={i} className="flex items-center justify-center">
                        {d !== null && (
                            <button onClick={() => setSelectedDate({y: viewYear, m: viewMonth, d})}
                                    className={`w-8 h-8 rounded-lg text-sm transition-all ${isSelected(d) ? 'bg-brand text-text-primary font-semibold' : isToday(d) ? 'text-brand border border-brand/50' : 'text-text-primary hover:bg-white/[0.08]'}`}>{d}</button>
                        )}
                    </div>
                ))}
            </div>
            <div className="flex items-center gap-3 px-4 py-3 border-t border-white/[0.08]">
                <div className="w-8 h-8 rounded-lg bg-brand-muted flex items-center justify-center"><Clock
                    className="w-4 h-4 text-brand"/></div>
                <div className="flex items-center gap-2 ml-auto">
                    <input type="number" value={hour} onFocus={e => e.target.select()} onChange={e => {
                        setHour(pad(Math.min(23, Math.max(0, Number(e.target.value)))));
                        if (e.target.value.length >= 2) minuteRef.current?.select()
                    }}
                           className="w-12 text-center rounded-lg py-1.5 text-text-primary text-sm bg-white/[0.08] border border-white/[0.12] outline-none focus:border-brand"/>
                    <span className="text-text-secondary">:</span>
                    <input ref={minuteRef} type="number" value={minute} onFocus={e => e.target.select()}
                           onChange={e => setMinute(pad(Math.min(59, Math.max(0, Number(e.target.value)))))}
                           className="w-12 text-center rounded-lg py-1.5 text-text-primary text-sm bg-white/[0.08] border border-white/[0.12] outline-none focus:border-brand"/>
                </div>
            </div>
            <div className="px-4 pb-4">
                <button onClick={() => setOpen(false)} disabled={!selectedDate}
                        className="w-full py-2.5 rounded-xl text-text-primary bg-brand shadow-brand-glow text-sm disabled:opacity-40">Confirm
                </button>
            </div>
        </div>
    )

    return (
        <div ref={triggerRef} className="relative w-full">
            <div
                onClick={() => setOpen(o => !o)}
                className={`flex items-center justify-between gap-2.5 px-3 py-2.5 rounded-xl cursor-pointer bg-surface border transition-colors h-[72px] ${error ? 'border-text-error' : open ? 'border-brand' : 'border-border'}`}
            >
                <div className="min-w-0 flex-1 flex flex-col justify-center">
                    <div className="text-xs text-text-secondary leading-tight">Scheduled at</div>
                    <div
                        className={`text-sm truncate font-medium ${value ? 'text-text-primary' : 'text-text-secondary'}`}>
                        {value ? formatDisplay(value) : 'Pick a date and time'}
                    </div>
                    <p className={`text-text-error text-[10px] leading-none h-3 mt-0.5 ${error ? 'visible' : 'invisible'}`}>{error ?? ''}</p>
                </div>
                <div className="w-8 h-8 rounded-lg bg-brand-muted flex items-center justify-center flex-shrink-0">
                    <Calendar className="w-4 h-4 text-brand"/>
                </div>
            </div>
            {open && createPortal(dropdown, document.body)}
        </div>
    )
}
